sudo: false

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

# command to install dependencies
install: 
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -q coverage


# command to run tests
script: PYTHONIOENCODING=ascii nosetests


after_success:
  - coveralls

