#!/usr/bin/env python2
import sys

from seesaw.script.run_warrior import main
import seesaw.six


if __name__ == '__main__':
    if not seesaw.six.PY2:
        raise Exception('This script expected Python 2 but got {0}.'
                        .format(sys.version))

    main()
