#!/usr/bin/env python
import sys
import os.path
from argparse import ArgumentParser

from seesaw.warrior import Warrior
from seesaw.web import start_warrior_server

def main():
  parser = ArgumentParser(description="Run the warrior web interface")
  parser.add_argument("projects_dir", metavar="DIRECTORY", type=str,
                      help="the warrior projects directory")
  parser.add_argument("data_dir", metavar="DIRECTORY", type=str,
                      help="the data directory")
  parser.add_argument("--port", dest="port_number",
                      help="the port number for the web interface (default: 8001)",
                      metavar="PORT", type=int, default=8001)
  args = parser.parse_args()

  warrior = Warrior(args.projects_dir, args.data_dir)
  
  start_warrior_server(warrior, port_number=args.port_number)

  warrior.start()


if __name__ == "__main__":
  main()

